# Welcome to numpy tutorial 

In [1]:
import numpy as np

In [2]:
myarr = np.array([3, 6, 3, 7], np.int8)

In [3]:
myarr

array([3, 6, 3, 7], dtype=int8)

# Array Creation: conversion from other python structure

**List**

In [4]:
listarray = np.array ([[1, 2, 3], [4, 5, 6], [7, 9, 8]])

In [5]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 9, 8]])

In [6]:
listarray.dtype

dtype('int64')

In [7]:
listarray.shape

(3, 3)

In [8]:
listarray.size

9

In [9]:
print (listarray.ndim)

2


**Dictionary**

In [10]:
np.array({32, 23, 23})


array({32, 23}, dtype=object)

# Intrinsic numpy array creation objects

In [11]:
zeros = np.zeros((2, 5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
zeros.dtype

dtype('float64')

In [13]:
zeros.shape

(2, 5)

**np.arange() :-** ***Used to create a NUmPy array with number of sequence.***

In [14]:
rng = np.arange(15)

In [15]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

**np.arange(start,stop, jump/steps) :-**   
***start :- starting value,   
                                            stop :- ending value(not including),   
                                            step :- gap between numbers***

In [16]:
rng = np.arange(1, 10, 2)

In [17]:
rng

array([1, 3, 5, 7, 9])

**lspace:-** ***Used to create equal number of space.***

**Syntax :-** np.lpspace(start, stop, Number_of_value)

In [18]:
lspace = np.linspace(1,5,12)

In [19]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [20]:
emp = np.empty((4,6))

In [21]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.86921958e-306, 1.42413555e-306, 1.78019082e-306],
       [1.37959740e-306, 6.23057349e-307, 1.02360935e-306,
        1.69120416e-306, 1.78022342e-306, 6.23058028e-307],
       [1.06811422e-306, 9.45699680e-308, 1.11258854e-306,
        1.11261502e-306, 1.42410839e-306, 7.56597770e-307],
       [6.23059726e-307, 1.42419530e-306, 1.11261027e-306,
        1.37961506e-306, 1.78019082e-306, 2.56765117e-312]])

In [22]:
emp_like = np.empty_like(lspace)

In [23]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [24]:
ide = np.identity(45)

In [25]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(45, 45))

In [26]:
ide.shape

(45, 45)

In [27]:
arr = np.arange(99)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [29]:
arr.reshape(3, 33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [31]:
arr = arr.reshape(3, 33)

In [32]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [33]:
arr = arr.ravel()

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [35]:
arr.shape 

(99,)

# Numpy Axis

In [36]:
x = [[1,2,3], [4,5,6], [7,1,0]] 

In [37]:
arra = np.array(x)

In [38]:
arra

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [39]:
arra.sum(axis=0)

array([12,  8,  9])

In [40]:
arra.sum(axis=1)

array([ 6, 15,  8])

In [41]:
arra.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [42]:
arra.flat

In [43]:
for item in arra.flat:
  print(item)

1
2
3
4
5
6
7
1
0


In [44]:
arra.ndim

2

In [45]:
arra.size

9

In [46]:
arra.nbytes

72

In [48]:
one = np.array([1, 2, 5, 634, 2])

In [50]:
one.argmax()

np.int64(3)

In [52]:
one.argmin()

np.int64(0)

In [53]:
one.argsort()

array([0, 1, 4, 2, 3])

In [54]:
arra

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [57]:
arra.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [58]:
arra.argmin()

np.int64(8)

In [59]:
arra.argmax()

np.int64(6)

In [64]:
arra.argmax(axis=0)

array([2, 1, 1])

In [65]:
arra.argmin(axis=0)

array([0, 2, 2])

In [66]:
arra.argmax(axis=1)

array([2, 2, 0])

In [67]:
arra.argmin(axis=1)

array([0, 0, 2])

In [68]:
arra.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [69]:
arra.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [71]:
arra.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [73]:
arra.reshape((9*1))

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [74]:
arra 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [76]:
arr = np.array([[1, 2, 3],
       [4, 0, 6],
       [8, 1, 0]])

In [77]:
arra + arr

array([[ 2,  4,  6],
       [ 8,  5, 12],
       [15,  2,  0]])

In [78]:
[324, 34] + [34, 546]

[324, 34, 34, 546]

In [79]:
arra * arr

array([[ 1,  4,  9],
       [16,  0, 36],
       [56,  1,  0]])

In [80]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 0.        , 2.44948974],
       [2.82842712, 1.        , 0.        ]])

In [82]:
arr.sum()

np.int64(25)

In [83]:
arr.max()

np.int64(8)

In [84]:
arr.min()

np.int64(0)

In [85]:
np.where(arr>5)

(array([1, 2]), array([2, 0]))

In [86]:
np.count_nonzero(arr)

np.int64(7)

In [87]:
arr

array([[1, 2, 3],
       [4, 0, 6],
       [8, 1, 0]])

In [88]:
import sys

In [92]:
py_ar = [0,4,55,2]

In [93]:
np_ar = np.array(py_ar)

In [94]:
sys.getsizeof(1) * len(py_ar)

112

In [95]:
np_ar.itemsize * np_ar.size

32

In [97]:
np_ar.tolist()

[0, 4, 55, 2]